# Generated by Django 3.2.16 on 2023-01-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_case_skips'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='model',
            field=models.FileField(default=None, null=True, upload_to='models'),
        ),
    ]
