# Generated by Django 3.2.16 on 2023-01-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_case_forecasting_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='forecasting_method',
        ),
        migrations.RemoveField(
            model_name='case',
            name='model',
        ),
    ]
