# Generated by Django 3.2.16 on 2023-01-12 05:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='skips',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
