# Generated by Django 3.2.16 on 2023-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_case_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='forecasting_method',
            field=models.CharField(choices=[('1', 'Grid Search'), ('2', 'pmdarima.arima.auto_arima')], default='1', max_length=1),
        ),
    ]
